# Generated by Django 4.2.7 on 2024-01-31 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Todo_List', '0002_alter_todo_task_bgcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_task',
            name='UserId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
